services:
  - type: web
    name: laravel-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_KEY
        value: base64:q+YooI/kstt08cWbLEW7eieIoMT+LNomx5IJtnrfLE8=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: 37.228.116.187
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: Test_Tonar
      - key: DB_USERNAME
        value: andy
      - key: DB_PASSWORD
        value: G00dW1nn
