version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
